title: Better.sg
baseurl: /
permalink: '/:title/'
color_scheme: light
accent_color: pink
header:
  has_nav: true
  logo_img: /images/betterwordlogo@0.5x.png
  title: Better.sg
footer:
  content: '&copy; better.sg All rights reserved.'
  has_social: true
  links:
    - new_window: true
      text: A product of Better.sg
      url: 'https://www.better.sg'
sass:
  indentWidth: 4
  precision: 10
  style: nested
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
